#!/usr/bin/env node
// Generates modules/<dir>/README.md and docs/modules.md from the lesson files,
// so the written docs can never drift from the SQL that actually runs.
import fs from 'node:fs';
import path from 'node:path';
import { root } from './db.mjs';
import { loadAllLessons, modulesDir } from './lessons.mjs';
import { c } from './render.mjs';

const GENERATED = '<!-- Generated by `npm run docs` from lesson.mjs. Do not edit by hand. -->';

function lessonMarkdown(lesson) {
  const lines = [
    GENERATED,
    '',
    `# Module ${lesson.id} · ${lesson.title}`,
    '',
    `${lesson.summary}`,
    '',
    `**Run it:** \`npm run lesson ${lesson.id}\`${lesson.duration ? ` · ~${lesson.duration}` : ''}`,
    '',
  ];

  if (lesson.objectives?.length) {
    lines.push('## Objectives', '');
    for (const objective of lesson.objectives) lines.push(`- ${objective}`);
    lines.push('');
  }

  lesson.steps.forEach((step, index) => {
    lines.push(`## ${index + 1}. ${step.title}`, '');
    if (step.explain) lines.push(step.explain, '');
    if (step.sql) {
      const statements = Array.isArray(step.sql) ? step.sql : [step.sql];
      lines.push('```sql', statements.map((s) => s.trim()).join('\n\n'), '```', '');
    }
    if (step.run && !step.sql) {
      lines.push('_This step runs a timed comparison in the CLI; see the runner output._', '');
    }
    if (step.takeaway) lines.push(`> **Takeaway** ${step.takeaway}`, '');
    if (step.note) lines.push(`> **Note** ${step.note}`, '');
  });

  if (lesson.challenge) {
    lines.push(
      '## Challenge',
      '',
      lesson.challenge.prompt,
      '',
      ...(lesson.challenge.hint ? [`_Hint: ${lesson.challenge.hint}_`, ''] : []),
      '<details><summary>Solution</summary>',
      '',
      '```sql',
      lesson.challenge.solution.trim(),
      '```',
      '',
      '</details>',
      '',
    );
  }

  if (lesson.next) lines.push('---', '', lesson.next, '');
  return lines.join('\n');
}

function indexMarkdown(lessons) {
  const lines = [
    GENERATED,
    '',
    '# Module index',
    '',
    '| # | Module | Time | What you learn |',
    '| --- | --- | --- | --- |',
  ];
  for (const lesson of lessons) {
    lines.push(
      `| ${lesson.id} | [${lesson.title}](../modules/${lesson.dir}/README.md) | ${lesson.duration || ''} | ${lesson.summary} |`,
    );
  }
  lines.push('', 'Run any module with `npm run lesson <id>`, for example `npm run lesson 04`.', '');
  return lines.join('\n');
}

async function main() {
  const lessons = await loadAllLessons();
  let written = 0;

  for (const lesson of lessons) {
    const file = path.join(modulesDir, lesson.dir, 'README.md');
    fs.writeFileSync(file, lessonMarkdown(lesson));
    written += 1;
    console.log(`  ${c.green('✓')} modules/${lesson.dir}/README.md`);
  }

  const indexFile = path.join(root, 'docs', 'modules.md');
  fs.writeFileSync(indexFile, indexMarkdown(lessons));
  console.log(`  ${c.green('✓')} docs/modules.md`);
  console.log(`\n  ${written + 1} file(s) generated from ${lessons.length} lesson(s).\n`);
}

main().catch((error) => {
  console.error(`\n  ${c.red('Docs generation failed:')} ${error.message}\n`);
  process.exitCode = 1;
});
